apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: node-js-sample
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: node-js-sample
    name: node-js-sample
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: node-js-sample:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/welshstew/node-js-sample.git
      secrets: []
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:0.10
          namespace: openshift
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: node-js-sample
    name: node-js-sample
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ${REGISTRY_IP}:5000/${IS_NAMESPACE}/node-js-sample:latest
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: node-js-sample
    name: node-js-sample
  spec:
    replicas: 1
    selector:
      app: node-js-sample
      deploymentconfig: node-js-sample
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/container.node-js-sample.image.entrypoint: '["container-entrypoint","/bin/sh","-c","$STI_SCRIPTS_PATH/usage"]'
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: node-js-sample
          deploymentconfig: node-js-sample
      spec:
        containers:
        - image: "${IS_NAMESPACE}/node-js-sample:latest"
          imagePullPolicy: Always
          name: node-js-sample
          env:
          - name: "PORT"
            value: "8080"
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - node-js-sample
        from:
          kind: ImageStreamTag
          name: node-js-sample:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: node-js-sample
    name: node-js-sample
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: node-js-sample
      deploymentconfig: node-js-sample
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: node-js-sample
    name: node-js-sample
  spec:
    host: node-js-sample-nodejs.rhel-cdk.10.1.2.2.xip.io
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: node-js-sample
parameters:
- name: "REGISTRY_IP"
  value: "172.30.123.229"
- name: "IS_NAMESPACE"
  value: "nodejs"
